In [1]:
# Numpy means numerical python

In [2]:
import numpy as np

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [11]:
np.arange(1,27,6)

array([ 1,  7, 13, 19, 25])

In [13]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.ones(18,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [25]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [26]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [27]:
np.random.rand(3,5)

array([[0.82561905, 0.64839465, 0.13139469, 0.79664632, 0.33936272],
       [0.76389212, 0.75558188, 0.34708492, 0.64814949, 0.22827452],
       [0.95380146, 0.22932234, 0.6031749 , 0.78939368, 0.02396308]])

In [29]:
np.random.rand(8,2)

array([[0.79120415, 0.72345807],
       [0.42596708, 0.62760788],
       [0.21028258, 0.60577971],
       [0.39631463, 0.31348216],
       [0.33811056, 0.68876857],
       [0.36178806, 0.15899384],
       [0.8767328 , 0.6237879 ],
       [0.91634815, 0.645093  ]])

In [31]:
np.random.randn(2,4)

array([[-0.07020344, -0.19560851,  0.9523476 ,  0.08373676],
       [ 1.037372  ,  0.00719773, -0.17707606,  0.1464358 ]])

In [33]:
arr=np.random.randn(2,4)
arr

array([[ 1.39619227, -1.15492748, -0.86982326, -0.97923237],
       [-0.26513936,  1.2026733 , -1.99204075, -0.10528733]])

In [36]:
np.random.randint(2,100)

19

In [37]:
np.random.randint(20,56,100)

array([24, 26, 25, 25, 30, 41, 31, 55, 37, 36, 45, 48, 21, 48, 43, 53, 34,
       45, 55, 26, 37, 24, 28, 48, 35, 44, 55, 28, 46, 46, 35, 50, 28, 46,
       38, 33, 28, 41, 21, 35, 53, 47, 54, 20, 39, 53, 45, 43, 53, 37, 33,
       21, 28, 33, 21, 47, 24, 50, 35, 45, 52, 31, 50, 31, 30, 50, 55, 55,
       27, 24, 37, 41, 38, 46, 36, 26, 41, 27, 53, 50, 40, 29, 46, 53, 38,
       41, 36, 40, 33, 45, 43, 26, 30, 20, 52, 35, 22, 30, 50, 36])

In [38]:
np.random.randint(12,41,50)

array([27, 23, 40, 18, 29, 25, 19, 13, 25, 26, 18, 23, 36, 17, 20, 19, 39,
       19, 19, 14, 13, 40, 27, 23, 21, 28, 39, 14, 25, 24, 32, 18, 12, 13,
       32, 23, 36, 21, 16, 27, 32, 14, 28, 34, 36, 26, 24, 24, 34, 37])

In [39]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
rand_array=np.random.randint(0,10,50)
rand_array

array([7, 4, 2, 9, 3, 3, 8, 7, 5, 6, 6, 5, 6, 0, 6, 1, 3, 7, 8, 1, 8, 1,
       2, 7, 2, 1, 1, 4, 9, 2, 7, 2, 6, 1, 6, 1, 9, 5, 9, 7, 8, 2, 6, 7,
       9, 8, 1, 7, 2, 3])

In [41]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [42]:
sample_array.reshape(4,5)

ValueError: cannot reshape array of size 30 into shape (4,5)

In [43]:
rand_array.max()

9

In [44]:
rand_array.argmax()

3

In [45]:
a=np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [46]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
a=np.random.rand(2,3)
a

array([[0.46930004, 0.88717373, 0.6364822 ],
       [0.33120138, 0.33624909, 0.92526928]])

In [50]:
a.T

array([[0.46930004, 0.33120138],
       [0.88717373, 0.33624909],
       [0.6364822 , 0.92526928]])

In [51]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
sample_array[0]

10

In [53]:
sample_array[2:5]

array([12, 13, 14])

In [54]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [55]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [57]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [58]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])